#include <system_error>
#include <cstdlib>
#include <jni.h>
#include <iostream>
#include <string>
#include <vector>
#include <algorithm>
#include <cmath>
#include <list>
#include <map>
#include <set>
#include <unordered_map> 
#include <unordered_set>
#include <fstream>
#include <memory>
#include <thread>
#include <chrono>
#include <exception>
#include <android/log.h>
