###########################
-keep class kotlin.** { *; }
-keep class kotlinx.** { *; }
-keep class androidx.** { *; }
-keep class android.support.v4.** { *; }
-keep class com.google.android.material.** { *; }
-keep class com.android.activity.** { *; }
-keep class xyn.xyn.xyn.** { *; }
-keep class org.jetbrains.annotations.** { *; }
-keep class org.intellij.lang.annotations.** { *; }
-keepattributes SourceFile,LineNumberTable
-renamesourcefileattribute SourceFile